POST http://localhost:8080/api/cadastro/salvar
Content-Type: application/json

{
  "nameUser": "string",
  "quantidadeMoradores": 0,
  "zonaEleitoral": "string",
  "fonteRenda": "string",
  "cep": "string",
  "cidade": "string",
  "agrovila": "string",
  "numeroCasa": 0,
  "educacao": true,
  "saneamento": true,
  "transporte": true,
  "saude": true,
  "agricultura": true,
  "esporteLazer": true
}
